version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV: development
      - HOST: 0.0.0.0
      - PORT: 3000
      - URL: 'url'
