version: "3.4"
services:    
  frontend:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/frontend
      - exclude:/frontend/node_modules/
    networks:
      - frontend
    environment:
      - NODE_ENV='development'
      - HOST=0.0.0.0
      - PORT=3000
      - URL='url'
volumes:
  exclude:
networks:
  frontend: