version: "3.4"
services:
  api:
    build: ./api 
    ports:
      - "8000:80"
    volumes:
      - .:/usr/local/app
    networks:
      - api
    
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - exclude:/frontend/node_modules/
    networks:
      - frontend
    environment:
      - NODE_ENV='development'
      - HOST=0.0.0.0
      - PORT=3000
      - URL='url'
volumes:
  exclude:
networks:
  frontend:
  api: